### ISSUE TITLE
[auto] - Subscription to the careathon 2024 - [Don't edit this title]

### ISSUE THREAD

**Issue by pythonbrad** [osscameroon/careathon-2024#15]
### What is your GitHub handle ?

pythonbrad

### What is the name of your team

CareCoders

### What is the GitHub handle of the second contestant ?

JoyRyane

### Which city do you live in ? (Dans quel ville vivez vous)

Douala

**Comment by rakici** [comment]
Hey @pythonbrad , thank you for registering to the careathon. I changed the issue title, and removed the third participant as it was a duplicate. Can you confirm that the current version of the issue description has the correct informations ?

**Comment by pythonbrad** [comment]
> Hey @pythonbrad , thank you for registering to the careathon. I changed the issue title, and removed the third participant as it was a duplicate. Can you confirm that the current version of the issue description has the correct informations ?

Thanks, it's ok now.
