### ISSUE TITLE
[auto] - Subscription to the careathon 2024 - [Don't edit this title]

### ISSUE THREAD

**Issue by KSI-Eesti** [osscameroon/careathon-2024#24]
### What is your GitHub handle ?

KSI-EESTI 

### Which city do you live in ? (Dans quel ville vivez vous)

Douala

**Comment by KSI-Eesti** [comment]
It is m'y first expérience and I am hoping to provide solutions to Help the Cameroonian population especially thé youth

**Comment by rakici** [comment]
> It is m'y first expérience and I am hoping to provide solutions to Help the Cameroonian population especially thé youth

I am sure you will.
