### ISSUE TITLE
[auto] - Inscription au careathon 2024 - [Ne modifiez pas ce titre]

### ISSUE THREAD

**Issue by ename1205** [osscameroon/careathon-2024#26]
### Quel est votre handle GitHub?

ename1205

### Dans quelle ville vivez vous?

Douala

**Comment by rakici** [comment]
Salut @ename1205 , merci pour votre inscription. Votre compte GitHub n'a pas suffisamment d'activite pour que nous puissions valider votre inscription. Si vous avez un compte Git lab, Bit bucket, linkedin ou tout autre informations qui justifient l'inactivite de ce compte, nous vous prions de nous les faire parvenir par email via hackaton@osscameroon.com.

**Comment by rakici** [comment]
No response
